.

diff --git a/igcc b/igcc
--- a/igcc
+++ b/igcc
@@ -16,21 +16,23 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
  
 readonly version="0.0.1"
-readonly copy="(C) 2018 TANI Kojiro <kojiro0531@gmail.com>"
+readonly copy="(C) 2018 TANI Kojiro <kojiro0531@gmail.com>
+(C) 2019 Zaoqi <zaomir@outlook.com>"
 
 lines=()
 count=0
 libs=()
-std=gnu11
+cmds=()
 if type clang >/dev/null 2>/dev/null; then
   cc=clang
-  ccversion=$(clang --version | grep ^clang)
 else
   cc=gcc
-  ccversion=$(gcc --version | grep ^gcc)
 fi
+ccversion(){
+  "$cc" -v 2>&1 | grep version
+}
 headers=(stdio.h)
-prog=$(basename $0)
+prog="$(basename $0)"
 script=""
 pre_scripts=()
 
@@ -52,51 +54,51 @@ function possible-completions () {
   local longest=""
   local word
   
-  for word in ${candidates[@]}; do
-    if [ ${#word} -gt ${#longest} ]; then
-      longest=$word
+  for word in "${candidates[@]}"; do
+    if [ "${#word}" -gt "${#longest}" ]; then
+      longest="$word"
     fi
   done
   local n=$((${#longest} + 5))
-  local cols=$(tput cols)
-  local fmt=$(printf "%%"$n"s%.0s" $(seq $((cols / n))))
-  printf ""$fmt"\n" ${candidates[@]}
+  local cols="$(tput cols)"
+  local fmt="$(printf "%%"$n"s%.0s" "$(seq $((cols / n)))")"
+  printf ""$fmt"\n" "${candidates[@]}"
 }
 
 readonly comp_wordbreaks=("(" ")" ";" "{" "}")
 
 function tab-complete () {
-  local words=($READLINE_LINE)
-  if [ $words ]; then
+  local words=("$READLINE_LINE")
+  if [ "$words" ]; then
     local slice=(${READLINE_LINE:0:$(($READLINE_POINT + 1))})
     local n=$((${#slice[@]} - 1))
 
     local break
-    for break in ${comp_wordbreaks[@]}; do
-      if [[ ${words[$n]} == $break* ]]; then
-        words[$n]="$(echo ${words[$n]} | cut -b 2-)"
+    for break in "${comp_wordbreaks[@]}"; do
+      if [[ "${words[$n]}" == "$break*" ]]; then
+        words[$n]="$(echo "${words[$n]}" | cut -b 2-)"
         break
       fi
       break=
     done
 
     local comp_words=(\
-      $(compgen -W "$(echo ${completion_candidates[@]})" -- ${words[n]}))
-    if [ ${#comp_words[@]} -eq 1 ]; then
+      "$(compgen -W "$(echo ${completion_candidates[@]})" -- "${words[n]}")")
+    if [ "${#comp_words[@]}" -eq 1 ]; then
       words[$n]=${comp_words[0]}
-    elif [ ${#comp_words[@]} -gt 1 ]; then
-      local prefix=$(printf "%s\n" "${comp_words[@]}" |\
-        sed -e '$!{N;s/^\(.*\).*\n\1.*$/\1\n\1/;D;}')
-      if [ $prefix = ${words[$n]} ]; then
+    elif [ "${#comp_words[@]}" -gt 1 ]; then
+      local prefix="$(printf "%s\n" "${comp_words[@]}" |\
+        sed -e '$!{N;s/^\(.*\).*\n\1.*$/\1\n\1/;D;}')"
+      if [ "$prefix" = "${words[$n]}" ]; then
         possible-completions "${comp_words[@]}"
       else
-        words[$n]=$prefix
+        words[$n]="$prefix"
       fi
     fi
     words[$n]="$break${words[$n]}"
-    READLINE_LINE=${words[@]}
+    READLINE_LINE="${words[*]}"
     slice="${words[@]:0:$(($n + 1))}"
-    READLINE_POINT=${#slice}
+    READLINE_POINT="${#slice}"
   else
     possible-completions
   fi
@@ -185,49 +187,49 @@ function create-source () {
     local body=""
   fi
   for ((i = 0; i < $count - 1; i++)); do
-    body+="({$(add-semicolon-if-needed ${lines[i]})"
+    body+="({$(add-semicolon-if-needed "${lines[i]}")"
   done
   if [ -z "$script" ]; then
     body+="({freopen(\"/dev/tty\", \"w\", stdout);"
   else
     body+="({;"
   fi
-  body+="$(add-semicolon-if-needed ${lines[i]})\
-    $(printf "});%.0s" ${lines[@]})"
+  body+="$(add-semicolon-if-needed "${lines[i]}")\
+    $(printf "});%.0s" "${lines[@]}")"
   local include="$(printf "#include \"%s\"\n" "${headers[@]}")"
   printf "%s\n%s\n$template\n" "$include" "$runtime" "$body"
 }
 
 function compile-and-run () { 
-  local bin=$(mktemp)
+  local bin="$(mktemp)"
   local src="$(create-source)"
   if [ -z "$script" ]; then
     local output="$(\
-      echo "$src" | "$cc" -xc -std=$std -o $bin -DPRINT \
-      -DCOUNT=$count ${libs[@]} - 2>&1 || \
-      echo "$src" | "$cc" -xc -std=$std -o $bin \
+      echo "$src" | "$cc" "${args[@]}" -xc -o "$bin" -DPRINT \
+      -DCOUNT=$count "${libs[@]}" - 2>&1 || \
+      echo "$src" | "$cc" "${args[@]}" -xc -o "$bin" \
       -DCOUNT=$count ${libs[@]} - 2>&1)"
   else
-    local output="$(echo $src | "$cc" -xc -std=$std -o $bin -DSCRIPT - 2>&1)"
+    local output="$(echo "$src" | "$cc" "${args[@]}" -xc -o "$bin" -DSCRIPT "${libs[@]}" - 2>&1)"
   fi
-  if [ -x $bin ]; then
+  if [ -x "$bin" ]; then
     if [ -z "$script" ]; then
-      local result="$($bin 2>&1 || echo failed)"
+      local result="$("$bin" 2>&1 || echo failed)"
       if [ ! -z "$result" ]; then
         let count--
         lines=(${lines[@]:0:$count})
         print-error "Segmentation fault."
       fi
     else
-      $bin || print-error "Segmentation fault"
+      "$bin" || print-error "Segmentation fault"
     fi
   else
     let count--
     lines=(${lines[@]:0:$count})
-    print-success "$(echo $output | grep -E error: | sort -u)"
+    print-success "$(echo "$output" | grep -E error: | sort -u)"
     print-error "Failed to compile."
   fi
-  rm -f $bin
+  rm -f "$bin"
 }
 
 function command-help () {
@@ -253,8 +255,8 @@ function command-clear () {
 }
 
 function command-edit () {
-  local file=$(mktemp)
-  local editor=${EDITOR:-vi}
+  local file="$(mktemp)"
+  local editor="${EDITOR:-vi}"
   
   if [ "${editor[0]}" = "vi" ] ||\
      [ "${editor[0]}" = "vim" ]; then
@@ -263,27 +265,27 @@ function command-edit () {
     echo "// -*- mode:c -*-" > $file
   fi
   
-  $editor $file
+  "$editor" "$file"
   
-  local content="$(sed "/^\/\/.*$/d" $file)"
-  rm -f $file
+  local content="$(sed "/^\/\/.*$/d" "$file")"
+  rm -f "$file"
   if [ -z "$content" ]; then
     print-error "Nothing to compile."
   else
-    lines+=("$(echo $content)")
+    lines+=("$(echo "$content")")
     let count++
     IFS= compile-and-run
   fi
 }
 
 function command-include () {
-  local header=$2
-  if [ -z $header ]; then
+  local header="$2"
+  if [ -z "$header" ]; then
     print-success "(${headers[*]})"
   else
-    if [ -z $(echo "${headers[@]}" | grep -o $header) ]; then
-      if [ -z $(echo \#include \"$header\" |\
-              "$cc" -xc - 2>&1 | grep -o $header) ]; then
+    if [ -z $(echo "${headers[@]}" | grep -o "$header") ]; then
+      if [ -z $(echo \#include \""$header"\" |\
+              "$cc" -xc - 2>&1 | grep -o "$header") ]; then
         headers+=("$header")
         print-success "(${headers[*]})"
       else
@@ -296,11 +298,11 @@ function command-include () {
 }
 
 function command-lib () {
-  local lib=$2
-  if [ -z $lib ]; then
+  local lib="$2"
+  if [ -z "$lib" ]; then
     print-success "(${libs[*]})"
   else
-    if [ -z $(echo "${libs[@]}" | grep -o $lib) ]; then
+    if [ -z "$(echo "${libs[@]}" | grep -o "$lib")" ]; then
       if [ -z "$("$cc" -l$2 2>&1 | grep -o main)" ]; then
         print-error "Could not find \`lib$lib.so\`."
       else
@@ -314,11 +316,11 @@ function command-lib () {
 }
 
 function command-load () {
-  local file=$2
-  if [ -z $file ]; then
+  local file="$2"
+  if [ -z "$file" ]; then
     print-error "Missing filename."
   else
-    if source $(realpath $file) >/dev/null 2>&1; then
+    if source "$(realpath "$file")" >/dev/null 2>&1; then
       print-success "Loaded.:\`$file\`"
     else
       print-error "Failed to load from \`$file\`."
@@ -327,11 +329,11 @@ function command-load () {
 }
 
 function command-save () {
-  local file=$2
-  if [ -z $file ]; then
+  local file="$2"
+  if [ -z "$file" ]; then
     print-error "Missing filename."
   else
-    cat << EOS > $file
+    cat << EOS > "$file"
 lib=(${libs[@]})
 headers=(${headers[@]})
 std=$std
@@ -343,25 +345,24 @@ EOS
 }
 
 function command-show () {
-  echo "$(
   local i
   for ((i=0; i < ${#headers[@]}; i++)); do
-    if [ $i -eq 0 ]; then
+    if [ "$i" -eq 0 ]; then
       printf "\e[34minclude\e[m: "
     else
       printf "       : "
     fi
-    printf "#include \"%s\"\n" ${headers[i]} |\
-      eval $indent | eval $highlight
+    printf "#include \"%s\"\n" "${headers[i]}" |\
+      eval "$indent" | eval "$highlight"
   done
 
   local line
   local flag=true
-  local _IFS=$IFS
+  local _IFS="$IFS"
   for ((i=0; i < $count; i++)); do
     IFS=$'\n'
     flag=true
-    for line in $(echo "${lines[i]}" | eval $indent | eval $highlight); do
+    for line in $(echo "${lines[i]}" | eval "$indent" | eval "$highlight"); do
       if $flag; then
         printf "\e[34m%7s\e[m: " "\$$(($i + 1))"
         flag=false
@@ -370,8 +371,8 @@ function command-show () {
       fi
       printf "%s\n" "$line"
     done
-    IFS=$_IFS
-  done)"
+    IFS="$_IFS"
+  done
 }
 
 function validate-line () {
@@ -389,7 +390,7 @@ function read-multiline () {
     sed -e "s/[[:cntrl:]]\[[0-9]*m//g" -e "s/././g" | cut -b 2-) "
   
   while true; do
-   if [ $(validate-line "${buf[@]}") -eq 1 ]; then
+   if [ "$(validate-line "${buf[@]}")" -eq 1 ]; then
       break
     fi
     if [ -z "$script" ]; then
@@ -474,7 +475,9 @@ Options:
   -v, --version        show version info and exit.
   -std <standard>      specify c dialect.
   -S, --script <file>  interpret file and exit.
-  -l, --load <file>    interpret file.
+  -r, --load <file>    interpret file.
+  -Pc <option>         pass <option> to "$cc".
+  -cc <compiler>       specify c compiler.
 EOS
   exit 1
 }
@@ -490,7 +493,7 @@ function set-std () {
     exit 1
   fi
   if echo | "$cc" -std="$1" -fsyntax-only -xc - >/dev/null 2>&1; then
-    std=$1
+    cmds+=("-std=$1")
   else
     print-error "Unrecognized option: $1"
     exit 1
@@ -500,6 +503,7 @@ function set-std () {
 function main () {
   local opt
   local scripts=()
+  local std
   for opt in "$@"; do
     case $opt in
       '-v' | '--version')
@@ -517,12 +521,22 @@ function main () {
         scripts+=("$(cat "$2" | sed -e '/^$/d')")
         shift 2
         ;;
-      '-l' | '--load')
+      '-r' | '--load')
         pre_scripts+=("$(cat "$2" | sed -e '/^$/d')")
         shift 2
         ;;
+      '-Pc')
+	cmds+=("$2")
+	shift 2
+	;;
+      '-cc')
+	cc="$2"
+	shift 2
+	;;
     esac
   done
+
+  [ ! -z "$std" ] && set-std "$std"
 
   if [ ! -z "$*" ]; then
     show-help-and-exit
@@ -532,7 +546,7 @@ function main () {
     echo "${scripts[*]}" | main-loop
   else
 cat << EOS
-$prog $version with $ccversion
+$prog $version with $(ccversion)
 $copy
 try \`:help\` to get help. Ctrl-C to exit.
 
